sudo: false
language: perl
perl:
  # - "5.32"
  - "5.30"
  - "5.28"
  - "5.26"
  - "5.24"
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
  - "5.8"
os:
  - linux
  - osx
osx_image:
  - "xcode12"
before_install:
  - $TRAVIS_BUILD_DIR/travis/before_install
script:
  - $TRAVIS_BUILD_DIR/travis/script
dist: xenial
