#!/bin/bash

. "$(dirname $0)/util.sh"

if [ $is_osx ]; then
    # I believe Travis does this for us now!
    # brew install cpanminus
    perlbrew available
fi

cpanm -n Devel::Cover Devel::Cover::Report::Coveralls CPAN::Meta JSON LWP::UserAgent

cpanm -n JSON
cpanm -n --installdeps .
