#!/bin/bash

. "$(dirname $0)/util.sh"

#make sure a cpan build will work
perl Makefile.PL
make manifest
make distdir
cd $(perl -MCPAN::Meta -e '$m = CPAN::Meta->load_file("MYMETA.yml"); print $m->name . "-" . $m->version')

perl Makefile.PL
cover -make "make TEST_VERBOSE=1" -test test
MQSSL=1 prove -MDevel::Cover -v  t/

cover -report coveralls
