#!/bin/bash

. "$(dirname $0)/util.sh"

#make sure a cpan build will work
perl Makefile.PL
make manifest
make distdir
cd $(perl -MCPAN::Meta -e '$m = CPAN::Meta->load_file("MYMETA.yml"); print $m->name . "-" . $m->version')

perl Makefile.PL
make test
cover -make "make TEST_VERBOSE=1 -I./blib/lib -I./blib/arch" -report coveralls -test test
# prove -MDevel::Cover -v  t/

# cover -test -report coveralls
